name: ros-foxy

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: ros:foxy

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Run rosdep install
        run: |
          rosdep update
          rosdep install -y --from-paths . --ignore-src --rosdistro foxy

      - name: Build
        run: |
          . /opt/ros/foxy/setup.sh
          colcon build --event-handlers console_cohesion+ \
            --cmake-args -DCMAKE_BUILD_TYPE=Release

      - name: Run tests
        run: |
          . /opt/ros/foxy/setup.sh
          colcon test \
           --event-handlers console_cohesion+ \
           --return-code-on-test-failure
